const state = {
  row: 12,
  col: 7,
  tik: './image/chikuwash_01.svg',
  toe: './image/chikuwash_02.svg',
  board: [
    [
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
    ],
    [
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
    ],
    [
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
    ],
    [
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
    ],
    [
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
    ],
    [
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
    ],
    [
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
    ],
    [
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
    ],
    [
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
    ],
    [
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
    ],
    [
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
    ],
    [
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
      { bin: 0, path: null, puyo: {} },
    ],
  ],
};

// debug
window['state'] = state;

export { state };
